version: '2'

services:
  bind:
    restart: always
    environment:
    - ROOT_PASSWORD=thisismysecret
    - WEBMIN_ENABLED=false
    image: sameersbn/bind:9.11.3-20190315
    ports:
    - "53:53/udp"
    - "53:53/tcp"
    - "10000:10000/tcp"
    volumes:
    - $PWD/data:/data
